<!DOCTYPE HTML>
<html>

<head>
	<title>DEL MOVER</title>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
	<link rel="stylesheet" href="/assets/css/main.css" />
</head>

<body>

	<!-- Header -->
	<header id="header">
		<div class="inner">
			<a href="index.html" class="logo">DELMOVER</a>
			<nav id="nav">
				<a href="/home/">DRIVER</a>
				<a href="/home/deliver">DELIVER</a>
			</nav>
		</div>
	</header>
	<a href="#menu" class="navPanelToggle"><span class="fa fa-bars"></span></a>

	<!-- Banner -->
	<section id="banner">
		<div class="inner">
			<h1>DELMOVER: <span>Your fast On-<br />
					Demand Courier Delivery!</span> <br />
				<p>ONE TAP AWAY DELIVERY</p>
			</h1>
			<ul class="actions">
				<li><a href="/admin/" class="button alt">Login</a></li>
				<li><a href="admin/pages/registration.php" class="button alt">Sign Up</a></li>
			</ul>
		</div>
	</section>

	<!-- Main -->
	<section id="main">
		<div class="inner">
			<header class="major special">
				<h1 class="h1-title-header">What can you deliver using DELMOVER</h1>
				<p>DELMOVER can provide courier services for your scheduled, on-demand, and same-day deliveries 24/7. From food delivery to grocery, and parcels of all shapes and sizes! </p>
			</header>
			<div class="box-alt">
				<div class="row 50% uniform">
					<div class="6u">
						<h5>Small Goods</h5>
						<span class="image fit">
							<img src="images/small-goods.png" alt="" />
						</span>
						<p>Good things come in small packages. Our on-demand delivery service will get yours quickly and safely to their destination anywhere within the Greater Manila Area.</p>
					</div>
					<div class="6u">
						<h5>Important Items</h5>
						<span class="image fit">
							<img src="images/important.png" alt="" />
						</span>
						<p>Have peace of mind when delivering documents, gadgets, even money through cash on delivery, with our real-time GPS tracking and in-house insurance*.* See Terms & Conditions for details.</p>
					</div>
				</div>
			</div>
		</div>
	</section>

	<!-- Footer -->
	<section id="footer">
		<div class="inner">
			<header>
				<h2>Mag inquire sa DELMOVER</h2>
			</header>
			<form method="post" action="#">
				<div class="field half first">
					<label for="name">Name</label>
					<input type="text" name="name" id="name" />
				</div>
				<div class="field half">
					<label for="email">Email</label>
					<input type="text" name="email" id="email" />
				</div>
				<div class="field">
					<label for="message">Message</label>
					<textarea name="message" id="message" rows="6"></textarea>
				</div>
				<ul class="actions">
					<li><input type="submit" value="Send Message" class="alt" /></li>
				</ul>
			</form>
			<div class="copyright">
				&copy; DEL MOVERS <span id="date"></span> . All Rights Reserved
			</div>
		</div>
	</section>

	<!-- Scripts -->
	<script src="/assets/js/jquery.min.js"></script>
	<script src="/assets/js/skel.min.js"></script>
	<script src="/assets/js/util.js"></script>
	<script src="/assets/js/main.js"></script>

	<!-- GET DATE FOR FOOTER-->
	<script type="text/javascript">
		n = new Date();
		y = n.getFullYear();
		document.getElementById("date").innerHTML = y;
	</script>
	<!-- END DATE-->
</body>

</html>