  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        User Profile
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">User</a></li>
        <li class="active">User profile</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-3">

          <!-- Profile Image -->
          <div class="box box-primary">
            <div class="box-body box-profile">
              <img class="profile-user-img img-responsive img-circle" src="/assets/dist/img/user4-128x128.jpg" alt="User profile picture">

              <h3 class="profile-username text-center"><?php echo $getUser; ?></h3>

              <ul class="list-group list-group-unbordered">
                <li class="list-group-item">
                  <b>Deliveries</b> <a class="pull-right">0</a>
                </li>
                <li class="list-group-item">
                  <b>Top Up</b> 
				  <a class="pull-right">
                  <?php
                  echo $getBalance;
				  ?>
				  </a>
                </li>
                <li class="list-group-item">
                  <b>Earnings</b> <a class="pull-right">0</a>
                </li>
              </ul>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->

          <!-- About Me Box -->
          <div class="box box-primary">
            <!-- /.box-header -->
            <div class="box-body">
              <strong><i class="fa fa-map-marker margin-r-5"></i> Location</strong>

              <p class="text-muted">Manila, Philippines</p>

              <hr>

              <strong><i class="fa fa-pencil margin-r-5"></i> Rate</strong>

              <p>
                <span class="label label-danger">5 Stars</span>
                <span class="label label-success">4 Stars</span>
                <span class="label label-info">3 Stars</span>
                <span class="label label-warning">2 Stars</span>
                <span class="label label-primary">1 Stars</span>
              </p>

              <hr>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
        <div class="col-md-9">
          <div class="nav-tabs-custom">
            <ul class="nav nav-tabs">
              <li class="active"><a href="#activity" data-toggle="tab">Activity</a></li>
            </ul>
            <div class="tab-content">
              <div class="active tab-pane" id="activity">
                <!-- Post -->
                <div class="post">
                  <!-- /.user-block -->
                  <?php
				  if(!$isAccountActivated)
				  {
				  ?>
                  <div class="row">
                    <div class="col-sm-12">
                      <h4>Before you can proceed here please download the delmover application on google play store and complete the requirements needed . Thank you.</h4>
                      <img class="img-responsive" src="/assets/dist/img/googleplaystore_image.png" alt="Photo">
                    </div>
                  </div>
				  <?php } else { ?>
				  <div class="row">
                    <div class="col-sm-12">
                      <!-- Chat box -->
					  <div class="box box-success">
						<div class="box-header">
						  <i class="fa fa-comments-o"></i>

						  <h3 class="box-title">History</h3>
						</div>
						<div class="box-body chat" id="chat-box">
						  <!-- chat item -->
						  <?php 
						  
						  foreach($userhistory as $data)
						  {
							echo '<div class="item">';
							echo '<img src="/assets/dist/img/user4-128x128.jpg" alt="user image" class="online">';
							echo '<p class="message">';
							echo '<a href="#" class="name">';
							echo '<small class="text-muted pull-right"><i class="fa fa-clock-o"></i>'.$data['date_log'].'</small>';
							echo 'Automated Message';
							echo '</a>';
							echo $data['log_message'];
							echo '</p>';
							echo '</div>';
						  }
						  
						  ?>
						</div>
					  </div>
					  <!-- /.box (chat box) -->
                    </div>
                  </div>
				  <?php }?>
                </div>
                <!-- /.post -->
              </div>
            </div>
            <!-- /.tab-content -->
          </div>
          <!-- /.nav-tabs-custom -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->