 <!-- Content Wrapper. Contains page content -->
 <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Top Up
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="#">User</li>
        <li class="active">Top up</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
	<?php 
	if(!$isAccountActivated)
	{
	?>
      <div class="error-page">
        <h2 class="headline text-red">505</h2>

        <div class="error-content">
          <h3><i class="fa fa-warning text-red"></i> This page is still blank</h3>
          <p>
            You need to complete first your requirements 
            before proceeding to this page.
          </p>
        </div>
      </div>
      <!-- /.error-page -->
	<?php } else {?>
		<div class="box box-info">
            <div class="box-header with-border">
              <h3 class="box-title">Horizontal Form</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
		<center><p id="errorAmount"></p></center>
            <form class="form-horizontal" id="user_topup">
              <div class="box-body">
                <div class="form-group">
                  <label for="amount" class="col-sm-2 control-label">Amount</label>
                  <div class="col-sm-10">
                    <input type="text" class="form-control" id="amount" name="amount" placeholder="Amount" required>
                  </div>
                </div>
              </div>
              <!-- /.box-body -->
              <div class="box-footer">
                <button type="submit"  name="submit" id="submit" class="btn btn-info pull-left">Request</button>
              </div>
              <!-- /.box-footer -->
            </form>
		</div>
		<p><center>Note: Delmover is not currently using any payment method due to security purposes. So we recommend to manually input and request it to the admin if you want to topup.</center></p>
	<p><center>After requesting wait for the admins approval and the admin will leave a message on your user profile for the confirmation that you can now topup.</center></p>
	<?php } ?>
	
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 1.0.0
    </div>
    <strong>Copyright &copy; 2020-<span id="date"></span> <a href="#">DELMOVER</a>.</strong> All rights
    reserved.
  </footer>
</div>
<!-- ./wrapper -->