
    <!-- Scripts -->
    <script src="/assets/js/jquery.min.js"></script>
    <script src="/assets/js/skel.min.js"></script>
    <script src="/assets/js/util.js"></script>
    <script src="/assets/js/main.js"></script>

    <!-- GET DATE FOR FOOTER-->
    <script type="text/javascript">
        n = new Date();
        y = n.getFullYear();
        document.getElementById("date").innerHTML = y;
    </script>
    <!-- END DATE-->
</body>

</html>