        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    Dashboard
                </h1>
                <ol class="breadcrumb">
                    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                    <li class="active">Dashboard</li>
                </ol>
            </section>

            <!-- Main content -->
            <section class="content">
                <!-- Small boxes (Stat box) -->
                <div class="row">
                    <div class="col-lg-3 col-xs-6">
                        <!-- small box -->
                        <div class="small-box bg-aqua">
                            <div class="inner">
                                <h3><?php echo $applicants; ?></h3>

                                <p>Applicants</p>
                            </div>
                            <div class="icon">
                                <i class="ion ion-person-add"></i>
                            </div>
                            <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
                        </div>
                    </div>
                    <!-- ./col -->
                    <div class="col-lg-3 col-xs-6">
                        <!-- small box -->
                        <div class="small-box bg-green">
                            <div class="inner">
                                <h3><?php echo $topuprequests; ?></h3>

                                <p>Top Up Request</p>
                            </div>
                            <div class="icon">
                                <i class="fa fa-money"></i>
                            </div>
                            <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
                        </div>
                    </div>
                    <!-- ./col -->
                    <div class="col-lg-3 col-xs-6">
                        <!-- small box -->
                        <div class="small-box bg-yellow">
                            <div class="inner">
                                <h3><?php echo $countDriver; ?></h3>

                                <p>Drivers</p>
                            </div>
                            <div class="icon">
                                <i class="fa fa-id-card"></i>
                            </div>
                            <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
                        </div>
                    </div>
                    <!-- ./col -->
                    <div class="col-lg-3 col-xs-6">
                        <!-- small box -->
                        <div class="small-box bg-red">
                            <div class="inner">
                                <h3>0</h3>

                                <p>App User Download</p>
                            </div>
                            <div class="icon">
                                <i class="ion ion-pie-graph"></i>
                            </div>
                            <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
                        </div>
                    </div>
                    <!-- ./col -->
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="box">
                            <div class="box-header">
                                <h3 class="box-title">Driver List</h3>
                            </div>
                            <!-- /.box-header -->
                            <div class="box-body table-responsive">
                                <table id="example1" class="table table-bordered table-striped">
                                    <thead>
                                        <tr>
                                            <th>Full Name</th>
                                            <th>Username</th>
                                            <th>TOP UP</th>
                                            <th>Address</th>
                                            <th>Phone Number</th>
                                            <th>Email Address</th>
                                            <th>Image</th>
                                            <th>NBI</th>
                                            <th>License</th>
                                            <th>OR/CR</th>
                                            <th>Image Vehicle Front</th>
                                            <th>Image Vehicle Back</th>
                                            <th>Vehicle Model</th>
                                            <th>Plate Number</th>
                                            <th>Training Date</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php
                                        foreach ($drivers as $data) {
                                            echo '<tr>';
                                            echo '<td>' . $data['fullname'] . '</td>';
                                            echo '<td>' . $data['username'] . '</td>';
                                            echo '<td>' . $data['top_up'] . '</td>';
                                            echo '<td>' . $data['address'] . '</td>';
                                            echo '<td>' . $data['phonenumber'] . '</td>';
                                            echo '<td>' . $data['emailaddress'] . '</td>';
                                            echo '<td><a href="' . str_replace("/assets/uploaded_images/", "", $data['image']) . '"><img src="' . str_replace("/assets/uploaded_images/", "", $data['image']) . '" class="img-responsive" style="width:100px;height:70px;"</a></td>';
                                            echo '<td><a href="' . str_replace("/assets/uploaded_images/", "", $data['image_nbi']) . '"><img src="' . str_replace("/assets/uploaded_images/", "", $data['image_nbi']) . '" class="img-responsive" style="width:100px;height:70px;"</a></td>';
                                            echo '<td><a href="' . str_replace("/assets/uploaded_images/", "", $data['image_license']) . '"><img src="' . str_replace("/assets/uploaded_images/", "", $data['image_license']) . '" class="img-responsive" style="width:100px;height:70px;"</a></td>';
                                            echo '<td><a href="' . str_replace("/assets/uploaded_images/", "", $data['image_or_cr']) . '"><img src="' . str_replace("/assets/uploaded_images/", "", $data['image_or_cr']) . '" class="img-responsive" style="width:100px;height:70px;"</a></td>';
                                            echo '<td><a href="' . str_replace("/assets/uploaded_images/", "", $data['image_front']) . '"><img src="' . str_replace("/assets/uploaded_images/", "", $data['image_front']) . '" class="img-responsive" style="width:100px;height:70px;"</a></td>';
                                            echo '<td><a href="' . str_replace("/assets/uploaded_images/", "", $data['image_back']) . '"><img src="' . str_replace("/assets/uploaded_images/", "", $data['image_back']) . '" class="img-responsive" style="width:100px;height:70px;"</a></td>';
                                            echo '<td>' . $data['vehicle_model'] . '</td>';
                                            echo '<td>' . $data['plate_number'] . '</td>';
                                            echo '<td>' . $data['training_date'] . '</td>';
                                            /* echo '<td><a href="/assets/model/message.php?id='.$data['id'].'" class="btn btn-success btn-circle"><i class="fa fa-envelope"></i></a></td>'; */
                                        }
                                        ?>
                                    </tbody>
                                    <!--  <tfoot>
                <tr>
                  <th>Rendering engine</th>
                  <th>Browser</th>
                  <th>Platform(s)</th>
                  <th>Engine version</th>
                  <th>CSS grade</th>
                </tr>
                </tfoot> -->
                                </table>
                            </div>
                            <!-- /.box-body -->
                        </div>
                    </div>
                </div>
                <!-- /.row (main row) -->

            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->